### ISSUE TITLE
Error | Scalping Depth

### ISSUE THREAD

**Issue by Tezeug** [kamilbl/NuBot#8]
![Screenshot_2019-04-01_23-05-15](https://user-images.githubusercontent.com/48736723/55359759-eac2a180-54d2-11e9-80f4-b48623d56ee2.png)
I've set the BTC budget in settings to 0.001.

Then I've set it to 0.0018 and got this error.
![Screenshot_2019-04-01_23-10-44](https://user-images.githubusercontent.com/48736723/55359986-6ae90700-54d3-11e9-966d-f79b1939bd47.png)

**Comment by kamilbl** [comment]
Ok ... It is very interesting :D One moment

**Comment by kamilbl** [comment]
I uploaded new file Strategy_SD.py. It is very Alfa version :D

**Comment by kamilbl** [comment]
First error been because you will wanted buy for <0.001BTC
4xNULS < 0.001BTC

**Comment by tezeug** [comment]
![f](https://user-images.githubusercontent.com/48736723/55362530-86a3db80-54da-11e9-95e0-3c6e37a9c7f2.png)

**Comment by tezeug** [comment]
I guess it is trying to buy it again although it is already bought.

**Comment by tezeug** [comment]
I've set the start operation to BUY.

**Comment by tezeug** [comment]
+ again string, not integer

**Comment by kamilbl** [comment]
Ok thanks for your testing ... I can check this in morning :D

**Comment by tezeug** [comment]
I've put these variable to strings and now it looks fine. But I got an another error :D. Look at it.
![t](https://user-images.githubusercontent.com/48736723/55363641-fd8ea380-54dd-11e9-8dcb-435674a26e1e.png)

**Comment by kamilbl** [comment]
Hello. 
I have a next version. And.... probably it's work... but if you set budget BTC = 0.0018 will be better if you will have a little more on binance wallet.

**Comment by tezeug** [comment]
Alright, this has worked well but I got the same error on the SELL operation.
![Screenshot_2019-04-02_13-40-09](https://user-images.githubusercontent.com/48736723/55400004-fc488f80-554c-11e9-90fb-bb66ae2ebb32.png)

**Comment by kamilbl** [comment]
Yes.... I know ... I need chaneg balanceBTC. Probably I use procent butget with your wallet. 
In strategy BB I have the same problem with balance... :/ 👎  :(

**Comment by tezeug** [comment]
Will you be able to fix it or is it quite a bigger problem?

**Comment by kamilbl** [comment]
Maybe Today I fix this problem... :D

**Comment by kamilbl** [comment]
How long are you will be online ?

**Comment by tezeug** [comment]
Till 1:00, maybe 2:00 (A. M.).

**Comment by tezeug** [comment]
I am checking GitHub and especially your NuBot’s repository quite often so I just will be waiting for the next release.

**Comment by kamilbl** [comment]
Thanks for your patience.

**Comment by tezeug** [comment]
When you fix it, I also have some other ideas on how to improve the strategy.

For example:
When the bot already buys the coin and then tries to sell it, it could be doing it like that. Look at it below. I guess the code looks pretty funny but I am sure you’ll understand it (hopefully :D).

while True:
     X = (just the set depth in the settings) 0.25 (%)
     fetch_bids
     if (highest_bid =< my_current_bid and profit(depth) => X):
          cancel_my_current_bid
          place_new_limit_bid(price = highest_bid-0.00000001)
     else:
          do nothing
          time.wait(1)

I am not sure if the bot already works like that or not because there is that error while putting a sell order and I haven’t checked the code much yet.

**Comment by tezeug** [comment]
I was trying to add there the correct spaces but I do not know GitHub formatting at all.

**Comment by kamilbl** [comment]
I uploaded new version Settings.py and Strategy_SD.py 🙂

**Comment by kamilbl** [comment]
I will draw a diagram. It will be easier to understand.

**Comment by tezeug** [comment]
I am currently testing it and waiting for some trade to be executed. So far, it has placed one buy order and then canceled it because the price went up so this is working fine yet:

**Comment by kamilbl** [comment]
🙂  I am waiting for your opinion. :D

**Comment by tezeug** [comment]
It is already working very well.
The bot has just sold the coins too.
But I would suggest a small improvement.
I see that the bot calculates the right time to execute the sell order based on the depth but not the profit (which practically is alright but the order could be profitable at some point and the bot would not sell just because of the market depth and then the price could dump and the trade end in a loss although it already was in profit).

Current trade looked like this.
NULS/BTC

Bought 9 NULS for 20,079 Satoshi.
The price went up and although it already caught the set amount of profit between the price for which it bought the coins and highest market bid (0.2 %, the highest bid was for 20,135 which is about 0.253 %) it was not selling because the market depth was not 0.2 %. What’s your opinion on that?

What about that the bot would put the order based on the market depth at first but then it would also seek for the amount of profit (which could be equal to the market depth % but would go on its own way).

**Comment by tezeug** [comment]
At least that’s what I think I saw but I am not 100 % sure I am correct so let me know your opinion. Maybe that it is correctly trading based on that and I am just wrong because I’ve not checked the code.

**Comment by tezeug** [comment]
Otherwise until now I have not encountered any errors, it looks really good including the information it logs about the current market situation and trades.

**Comment by tezeug** [comment]
![80192AA6-D006-4061-A810-14B23F0C8F61](https://user-images.githubusercontent.com/48736723/55422674-79d7c400-557c-11e9-9ed1-abca1f861bbe.jpeg)
The Telegram bot looks like this.

**Comment by kamilbl** [comment]
Thanks for your feedback. 
1) In this strategy I did not add telegram msg. In next update will be :D
2) I have a ideas ... We buy coins for 1000 Satoshi, and we want pofit 0,3% with this order. Depth market is 0.5%. But we don't want waiting because profit is "done". The final Bot sell coins for 1000x1.003 = 1003 Satoshi. What do you think ?

**Comment by tezeug** [comment]
That’s also what I was thinking about and exactly it would be very good in my opinion.

= the bot would not just work with the depth because it can also go into negative profit but with the profit percentage too

**Comment by tezeug** [comment]
![07F5F4BF-B77A-41C7-998B-717D79579FBD](https://user-images.githubusercontent.com/48736723/55425032-ce317280-5581-11e9-9763-39993f704d4c.jpeg)
This is exactly the situation.
The profit was under 0.2 % but the depth was more than 0.2 % so the bot sold the coins although the trde already could be in a loss.

**Comment by tezeug** [comment]
The profit here is just 0.045 % but the depth was more than 0.2 %.

**Comment by kamilbl** [comment]
I will make schemat and we can look where need add upgrade code...

**Comment by tezeug** [comment]
I see a new update but am not sure what is new. Should I test it?

**Comment by kamilbl** [comment]
You can test RSI, BB, PIngPong, PingPong2, PingPongSMA. I am testing PIngPongSMA 🙂

**Comment by tezeug** [comment]
Just turned PPSMA on too.

**Comment by tezeug** [comment]
The Telegram messages could later look somehow like this.

===== Bought / Sold =====
Price: 0.000247 BTC
Amount: 0.0174 BTC
Profit/Loss: 0.00005795 BTC
=====================

And then it could also send message e. g. every hour:

The bot has made 12 trades so far and the profit/loss is 0.0055 BTC.
